sudo: false
language: c
script: ls -a build_lib && autoreconf -i && ./configure && make && ls -a build_lib
cache:
  directories:
  - build_lib
addons:
  apt:
    packages:
    - check
    - openssl
    - libbsd-dev
    - valgrind
services:
  - mysql
  - memcached
